/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.infnet.visao;

import br.edu.infnet.modelo.Funcionario;
import br.edu.infnet.validador.ValidaFuncionarioException;
import br.edu.infnet.repository.FuncionarioRepository;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel Farias
 */
public class Janela extends javax.swing.JFrame {

    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPrincipal = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        START = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        abaCadastrarFuncionario = new javax.swing.JPanel();
        nome = new javax.swing.JLabel();
        empresa = new javax.swing.JLabel();
        empresa1 = new javax.swing.JLabel();
        empresa2 = new javax.swing.JLabel();
        campoTextoNome = new javax.swing.JTextField();
        campoTextoEmpresa = new javax.swing.JTextField();
        campoTextoSalario = new javax.swing.JTextField();
        campoTextoProfissao = new javax.swing.JTextField();
        Salvar = new javax.swing.JButton();
        CadastroDeFuncionarios = new javax.swing.JLabel();
        abaConsultarFuncionario = new javax.swing.JPanel();
        Buscar = new javax.swing.JLabel();
        campoBuscarFuncionario = new javax.swing.JTextField();
        painelResultados = new javax.swing.JScrollPane();
        botaoBuscar = new javax.swing.JButton();
        consultaFuncionários = new javax.swing.JLabel();
        abaExibirFuncionario = new javax.swing.JPanel();
        ID = new java.awt.Label();
        nomeExibir = new java.awt.Label();
        nomeExibir1 = new java.awt.Label();
        nomeExibir2 = new java.awt.Label();
        nomeExibir3 = new java.awt.Label();
        campoTextoExibirEmpresa = new javax.swing.JTextField();
        campoTextoExibirID = new javax.swing.JTextField();
        campoTextoExibirNome = new javax.swing.JTextField();
        campoTextoExibirProfissao = new javax.swing.JTextField();
        campoTextoExibirSalario = new javax.swing.JTextField();
        BotaoRemoverFuncionario = new javax.swing.JButton();
        BotaoAtualizarFuncionario1 = new javax.swing.JButton();
        exibirFuncionários = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PainelPrincipal.setBackground(new java.awt.Color(0, 153, 153));
        PainelPrincipal.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        PainelPrincipal.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Desenvolvimento JAVA");

        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("PROJETO DE BLOCO");

        jLabel3.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 12)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Teste de Performace - TP 4");

        START.setBackground(java.awt.Color.red);
        START.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        START.setForeground(java.awt.Color.white);
        START.setText("START");
        START.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STARTActionPerformed(evt);
            }
        });

        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Programa Desenvolvido por Daniel Farias");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(START, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(76, 76, 76)
                .addComponent(START, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        PainelPrincipal.addTab("Apresentação", jPanel1);

        abaCadastrarFuncionario.setBackground(new java.awt.Color(0, 153, 153));

        nome.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        nome.setForeground(java.awt.Color.white);
        nome.setText("Nome:");

        empresa.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        empresa.setForeground(java.awt.Color.white);
        empresa.setText("Empresa:");

        empresa1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        empresa1.setForeground(java.awt.Color.white);
        empresa1.setText("Profissão:");

        empresa2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        empresa2.setForeground(java.awt.Color.white);
        empresa2.setText("Salário:");

        campoTextoSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoSalarioActionPerformed(evt);
            }
        });

        Salvar.setBackground(java.awt.Color.red);
        Salvar.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        Salvar.setForeground(java.awt.Color.white);
        Salvar.setText("SALVAR");
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });

        CadastroDeFuncionarios.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        CadastroDeFuncionarios.setForeground(java.awt.Color.white);
        CadastroDeFuncionarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CadastroDeFuncionarios.setText("CADASTRO DE FUNCIONÁRIOS:");

        javax.swing.GroupLayout abaCadastrarFuncionarioLayout = new javax.swing.GroupLayout(abaCadastrarFuncionario);
        abaCadastrarFuncionario.setLayout(abaCadastrarFuncionarioLayout);
        abaCadastrarFuncionarioLayout.setHorizontalGroup(
            abaCadastrarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaCadastrarFuncionarioLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(abaCadastrarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(abaCadastrarFuncionarioLayout.createSequentialGroup()
                        .addGroup(abaCadastrarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(empresa2)
                            .addComponent(empresa1)
                            .addComponent(empresa)
                            .addComponent(nome))
                        .addGap(46, 46, 46)
                        .addGroup(abaCadastrarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoTextoNome)
                            .addComponent(campoTextoEmpresa)
                            .addComponent(campoTextoSalario)
                            .addComponent(campoTextoProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(CadastroDeFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        abaCadastrarFuncionarioLayout.setVerticalGroup(
            abaCadastrarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaCadastrarFuncionarioLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(CadastroDeFuncionarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(abaCadastrarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome)
                    .addComponent(campoTextoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(abaCadastrarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empresa)
                    .addComponent(campoTextoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(abaCadastrarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empresa1)
                    .addComponent(campoTextoProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(abaCadastrarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empresa2)
                    .addComponent(campoTextoSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        PainelPrincipal.addTab("Cadastrar Funcionário", abaCadastrarFuncionario);

        abaConsultarFuncionario.setBackground(new java.awt.Color(0, 153, 153));

        Buscar.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        Buscar.setForeground(java.awt.Color.white);
        Buscar.setText("Busca:");

        botaoBuscar.setBackground(java.awt.Color.red);
        botaoBuscar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        botaoBuscar.setForeground(new java.awt.Color(255, 255, 255));
        botaoBuscar.setText("Buscar");
        botaoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarActionPerformed(evt);
            }
        });

        consultaFuncionários.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        consultaFuncionários.setForeground(java.awt.Color.white);
        consultaFuncionários.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        consultaFuncionários.setText("CONSULTA DE FUNCIONÁRIOS:");

        javax.swing.GroupLayout abaConsultarFuncionarioLayout = new javax.swing.GroupLayout(abaConsultarFuncionario);
        abaConsultarFuncionario.setLayout(abaConsultarFuncionarioLayout);
        abaConsultarFuncionarioLayout.setHorizontalGroup(
            abaConsultarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaConsultarFuncionarioLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(abaConsultarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(painelResultados)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, abaConsultarFuncionarioLayout.createSequentialGroup()
                        .addGroup(abaConsultarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, abaConsultarFuncionarioLayout.createSequentialGroup()
                                .addComponent(Buscar)
                                .addGap(18, 18, 18)
                                .addComponent(campoBuscarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botaoBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(consultaFuncionários, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(31, 31, 31))
        );
        abaConsultarFuncionarioLayout.setVerticalGroup(
            abaConsultarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaConsultarFuncionarioLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(consultaFuncionários)
                .addGroup(abaConsultarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaConsultarFuncionarioLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(abaConsultarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoBuscarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoBuscar)))
                    .addGroup(abaConsultarFuncionarioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Buscar)))
                .addGap(18, 18, 18)
                .addComponent(painelResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        PainelPrincipal.addTab("Consultar Funcionario", abaConsultarFuncionario);

        abaExibirFuncionario.setBackground(new java.awt.Color(0, 153, 153));

        ID.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ID.setForeground(java.awt.Color.white);
        ID.setText("ID:");

        nomeExibir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nomeExibir.setForeground(java.awt.Color.white);
        nomeExibir.setText("Empresa:");

        nomeExibir1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nomeExibir1.setForeground(java.awt.Color.white);
        nomeExibir1.setText("Profissão:");

        nomeExibir2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nomeExibir2.setForeground(java.awt.Color.white);
        nomeExibir2.setText("Nome:");

        nomeExibir3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nomeExibir3.setForeground(java.awt.Color.white);
        nomeExibir3.setText("Salário:");

        BotaoRemoverFuncionario.setBackground(java.awt.Color.red);
        BotaoRemoverFuncionario.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        BotaoRemoverFuncionario.setForeground(java.awt.Color.white);
        BotaoRemoverFuncionario.setText("Remover");
        BotaoRemoverFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRemoverFuncionarioActionPerformed(evt);
            }
        });

        BotaoAtualizarFuncionario1.setBackground(java.awt.Color.red);
        BotaoAtualizarFuncionario1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        BotaoAtualizarFuncionario1.setForeground(java.awt.Color.white);
        BotaoAtualizarFuncionario1.setText("Atualizar");
        BotaoAtualizarFuncionario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAtualizarFuncionario1ActionPerformed(evt);
            }
        });

        exibirFuncionários.setAlignment(java.awt.Label.CENTER);
        exibirFuncionários.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        exibirFuncionários.setForeground(java.awt.Color.white);
        exibirFuncionários.setText("EXIBIÇÃO DE FUNCIONÁRIOS:");

        javax.swing.GroupLayout abaExibirFuncionarioLayout = new javax.swing.GroupLayout(abaExibirFuncionario);
        abaExibirFuncionario.setLayout(abaExibirFuncionarioLayout);
        abaExibirFuncionarioLayout.setHorizontalGroup(
            abaExibirFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaExibirFuncionarioLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(abaExibirFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(exibirFuncionários, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(abaExibirFuncionarioLayout.createSequentialGroup()
                        .addGroup(abaExibirFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(abaExibirFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nomeExibir2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(abaExibirFuncionarioLayout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(nomeExibir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeExibir1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeExibir3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(abaExibirFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoTextoExibirEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoTextoExibirID, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoTextoExibirNome, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoTextoExibirProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoTextoExibirSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(abaExibirFuncionarioLayout.createSequentialGroup()
                                .addComponent(BotaoAtualizarFuncionario1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotaoRemoverFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        abaExibirFuncionarioLayout.setVerticalGroup(
            abaExibirFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaExibirFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exibirFuncionários, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(abaExibirFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTextoExibirID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(abaExibirFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeExibir2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTextoExibirNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(abaExibirFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nomeExibir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTextoExibirEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(abaExibirFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeExibir1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTextoExibirProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(abaExibirFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeExibir3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTextoExibirSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abaExibirFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoRemoverFuncionario)
                    .addComponent(BotaoAtualizarFuncionario1))
                .addContainerGap())
        );

        ID.getAccessibleContext().setAccessibleName("ID");
        ID.getAccessibleContext().setAccessibleDescription("");

        PainelPrincipal.addTab("Exibir Funcionario", abaExibirFuncionario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PainelPrincipal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PainelPrincipal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoAtualizarFuncionario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAtualizarFuncionario1ActionPerformed
        String id = campoTextoExibirID.getText();
        String nome = campoTextoExibirNome.getText();
        String empresa = campoTextoExibirEmpresa.getText();
        String profissao = campoTextoExibirProfissao.getText();
        String salario = campoTextoExibirSalario.getText();
        String salarioSemVirgula = salario.replaceAll(",", "\\.");

        if (nome == null || empresa == null || profissao == null || salario == null) {
            JOptionPane.showMessageDialog(null, "Funcionário inválido. Todos os campos devem ser preenchidos.");
        }

        try {
            Double salarioDb = Double.parseDouble(salarioSemVirgula);
            String salarioStr = salarioDb.toString();
            int i = Integer.parseInt(id);
            if (salarioDb > 0 && i >= 0) {
                validaFuncionario(nome, empresa, profissao);
                FuncionarioRepository funcionarioRepository = new FuncionarioRepository();
                funcionarioRepository.editarFuncionario(i, nome, empresa, profissao, salarioStr);
                JOptionPane.showMessageDialog(null, "Funcionário Atualizado com sucesso.");
                campoTextoExibirID.setText("");
                campoTextoNome.setText("");
                campoTextoExibirEmpresa.setText("");
                campoTextoExibirProfissao.setText("");
                campoTextoExibirSalario.setText("");
                PainelPrincipal.setSelectedComponent(abaConsultarFuncionario);
            } else {
                JOptionPane.showMessageDialog(null, "O salário ou o ID devem ter um valor maior que ZERO.");
            }

        } catch (ValidaFuncionarioException e) {
            JOptionPane.showMessageDialog(null, "Funcionário inválido. O nome, a empresa ou a profissão estão incorretos.");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "O salário ou o ID devem ter um valor válido.");
        }
    }//GEN-LAST:event_BotaoAtualizarFuncionario1ActionPerformed

    private void BotaoRemoverFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRemoverFuncionarioActionPerformed
        String id = campoTextoExibirID.getText();
        FuncionarioRepository funcionarioRepository = new FuncionarioRepository();
        funcionarioRepository.remover(Integer.parseInt(id));
        JOptionPane.showMessageDialog(null, "Funcionário removido com Sucesso!");
        PainelPrincipal.setSelectedComponent(abaConsultarFuncionario);
    }//GEN-LAST:event_BotaoRemoverFuncionarioActionPerformed

    private void botaoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarActionPerformed
        String busca = campoBuscarFuncionario.getText();
        FuncionarioRepository funcionarioRepository = new FuncionarioRepository();
        ArrayList<Funcionario> lista = funcionarioRepository.buscarFuncionario(busca);
        JList<Funcionario> listaFuncionario = new JList();
        DefaultListModel<Funcionario> model = new DefaultListModel();
        for (Funcionario funcionario : lista) {
            model.addElement(funcionario);
        }
        listaFuncionario.setModel(model);
        painelResultados.setViewportView(listaFuncionario);
        painelResultados.setVisible(true);

        listaFuncionario.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                Funcionario funcionario = listaFuncionario.getSelectedValue();
                campoTextoExibirID.setText(funcionario.getId().toString());
                campoTextoExibirNome.setText(funcionario.getNome());
                campoTextoExibirEmpresa.setText(funcionario.getEmpresa());
                campoTextoExibirProfissao.setText(funcionario.getProfissão());
                campoTextoExibirSalario.setText(funcionario.getSalario());
                PainelPrincipal.setSelectedComponent(abaExibirFuncionario);
            }
        });

    }//GEN-LAST:event_botaoBuscarActionPerformed

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
        String nome = campoTextoNome.getText();
        String empresa = campoTextoEmpresa.getText();
        String profissao = campoTextoProfissao.getText();
        String salario = campoTextoSalario.getText();
        String salarioSemVirgula = salario.replaceAll(",", "\\.");

        if (nome == null || empresa == null || profissao == null || salario == null) {
            JOptionPane.showMessageDialog(null, "Funcionário inválido. Todos os campos devem ser preenchidos.");
        }

        try {

            Double salarioDb = Double.parseDouble(salarioSemVirgula);
            String salarioStr = salarioDb.toString();
            if (salarioDb > 0) {
                validaFuncionario(nome, empresa, profissao);
                FuncionarioRepository funcionarioRepository = new FuncionarioRepository();
                funcionarioRepository.salvar(nome, empresa, profissao, salarioStr);
                JOptionPane.showMessageDialog(null, "Funcionário Salvo com sucesso.");
                campoTextoNome.setText("");
                campoTextoEmpresa.setText("");
                campoTextoProfissao.setText("");
                campoTextoSalario.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "O salário deve ser um valor maior que ZERO.");
            }

        } catch (ValidaFuncionarioException e) {
            JOptionPane.showMessageDialog(null, "Funcionário inválido. O nome, a empresa ou a profissão estão incorretos.");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "O salário deve ser um valor válido.");
        }
    }//GEN-LAST:event_SalvarActionPerformed

    private void campoTextoSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoSalarioActionPerformed

    private void STARTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STARTActionPerformed
        JOptionPane.showMessageDialog(null, "Bem vindo ao Sistema de cadastro de Funcionário!");
        PainelPrincipal.setSelectedComponent(abaCadastrarFuncionario);
    }//GEN-LAST:event_STARTActionPerformed

    public void validaFuncionario(String nome, String empresa, String profissao) throws ValidaFuncionarioException {

        if (nome == null || empresa == null || profissao == null) {
            ValidaFuncionarioException validaFuncionarioException = new ValidaFuncionarioException();
            throw validaFuncionarioException;
        }

        if (nome.trim().length() < 3 || empresa.trim().length() < 3 ) {
            ValidaFuncionarioException validaFuncionarioException = new ValidaFuncionarioException();
            throw validaFuncionarioException;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAtualizarFuncionario1;
    private javax.swing.JButton BotaoRemoverFuncionario;
    private javax.swing.JLabel Buscar;
    private javax.swing.JLabel CadastroDeFuncionarios;
    private java.awt.Label ID;
    private javax.swing.JTabbedPane PainelPrincipal;
    private javax.swing.JButton START;
    private javax.swing.JButton Salvar;
    private javax.swing.JPanel abaCadastrarFuncionario;
    private javax.swing.JPanel abaConsultarFuncionario;
    private javax.swing.JPanel abaExibirFuncionario;
    private javax.swing.JButton botaoBuscar;
    private javax.swing.JTextField campoBuscarFuncionario;
    private javax.swing.JTextField campoTextoEmpresa;
    private javax.swing.JTextField campoTextoExibirEmpresa;
    private javax.swing.JTextField campoTextoExibirID;
    private javax.swing.JTextField campoTextoExibirNome;
    private javax.swing.JTextField campoTextoExibirProfissao;
    private javax.swing.JTextField campoTextoExibirSalario;
    private javax.swing.JTextField campoTextoNome;
    private javax.swing.JTextField campoTextoProfissao;
    private javax.swing.JTextField campoTextoSalario;
    private javax.swing.JLabel consultaFuncionários;
    private javax.swing.JLabel empresa;
    private javax.swing.JLabel empresa1;
    private javax.swing.JLabel empresa2;
    private java.awt.Label exibirFuncionários;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nome;
    private java.awt.Label nomeExibir;
    private java.awt.Label nomeExibir1;
    private java.awt.Label nomeExibir2;
    private java.awt.Label nomeExibir3;
    private javax.swing.JScrollPane painelResultados;
    // End of variables declaration//GEN-END:variables
}
